name: Publish new version

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - package.json

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/checkout@v4

      - name: Publish to NPM
        run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN_NPM }}